call plug#begin('~/.vim/plugged')
Plug 'scrooloose/nerdtree'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'mhinz/vim-signify'
Plug 'Yggdroot/indentLine'
Plug 'graywh/vim-colorindent'
Plug 'flazz/vim-colorschemes'
Plug 'nathanaelkane/vim-indent-guides'
call plug#end()
