call plug#begin('~/.vim/plugged')
Plug 'scrooloose/nerdtree'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'mhinz/vim-signify'
Plug 'Yggdroot/indentLine'
Plug 'flazz/vim-colorschemes'
Plug 'vim-scripts/taglist.vim'
Plug 'tpope/vim-fugitive'
Plug 'Valloric/YouCompleteMe',{'do':'./install.py'}
Plug 'rhysd/vim-clang-format'
Plug 'vim-scripts/autoload_cscope.vim'
call plug#end()
